exclude:
  - EDB_PROSE/
  - JEKYLL_DB/
prose:
  # rooturl: "_posts"
  siteurl: 'http://prose.io/#mklarmann/edb-test/'
  ignore:
    # - _prose.yml
  metadata:
    _posts:
      - name: "MODID"
        field:
          element: "text"
          label: "MOID"
      - name: "RECORDID"
        field:
          element: "text"
          label: "RECORDID"
      - name: "ID"
        field:
          element: "text"
          label: "ID"
      - name: "Name_Deutsch"
        field:
          element: "text" 
          label: "Name_Deutsch"
      - name: "Std_Herkunft"
        field:
          element: "text" 
          label: "Std_Herkunft"
      - name: "kg_CO2"
        field:
          element: "text"
          label: "kg_CO2" 
      - name: "Alternativen"
        field:
          element: "text"
          label: "Alternativen" 
      - name: "Auswahl_sortieren"
        field:
          element: "text" 
          label: "Auswahl_sortieren"
      - name: "Autor"
        field:
          element: "text"
          label: "Autor" 
      - name: "Backgroundinfo"
        field:
          element: "text" 
          label: "Backgroundinfo"
      - name: "Beschreibung"
        field:
          element: "text"
          label: "Beschreibung" 
      - name: "CO2_Berechnung"
        field:
          element: "text"
          label: "CO2_Berechnung" 
      - name: "CO2_log"
        field:
          element: "text"
          label: "CO2_log" 